--------------------------------------------------------
--  Constraints for Table POSLEDNI_UKOL_POZADAVKU
--------------------------------------------------------

  ALTER TABLE "HR"."POSLEDNI_UKOL_POZADAVKU" ADD CONSTRAINT "POSLEDNI_UKOL_PK" PRIMARY KEY ("UKOLY_ID", "POZADAVKY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."POSLEDNI_UKOL_POZADAVKU" MODIFY ("UKOLY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."POSLEDNI_UKOL_POZADAVKU" MODIFY ("POZADAVKY_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."POSLEDNI_UKOL_POZADAVKU" MODIFY ("DATUM_I" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."POSLEDNI_UKOL_POZADAVKU" MODIFY ("UZIV_I" NOT NULL ENABLE);
