--------------------------------------------------------
--  Constraints for Table POZADAVKY
--------------------------------------------------------

  ALTER TABLE "HR"."POZADAVKY" ADD CONSTRAINT "JEDNACI_CISLO_UK" UNIQUE ("JEDNACI_CISLO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."POZADAVKY" ADD CONSTRAINT "POZADAVKY_ID_PK" PRIMARY KEY ("POZADAVKY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."POZADAVKY" MODIFY ("DATUM_I" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."POZADAVKY" MODIFY ("UZIV_I" NOT NULL ENABLE);
