--------------------------------------------------------
--  Constraints for Table POZADAVEK_STAV
--------------------------------------------------------

  ALTER TABLE "HR"."POZADAVEK_STAV" ADD CONSTRAINT "POZADAVEK_STAV_ID_PK" PRIMARY KEY ("POZADAVEK_STAV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."POZADAVEK_STAV" MODIFY ("POZADAVEK_STAV" CONSTRAINT "POZADAVEK_STAV_NN" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."POZADAVEK_STAV" ADD CONSTRAINT "POZADAVEK_STAV_UK" UNIQUE ("POZADAVEK_STAV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."POZADAVEK_STAV" MODIFY ("DATUM_I" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."POZADAVEK_STAV" MODIFY ("UZIV_I" NOT NULL ENABLE);
