--------------------------------------------------------
--  Constraints for Table POZADAVEK_TYP
--------------------------------------------------------

  ALTER TABLE "HR"."POZADAVEK_TYP" ADD CONSTRAINT "POZADAVEK_TYP_ID_PK" PRIMARY KEY ("POZADAVEK_TYP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."POZADAVEK_TYP" MODIFY ("POZADAVEK_TYP" CONSTRAINT "POZADAVEK_TYP_NN" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."POZADAVEK_TYP" ADD CONSTRAINT "POZADAVEK_TYP_UK" UNIQUE ("POZADAVEK_TYP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."POZADAVEK_TYP" MODIFY ("DATUM_I" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."POZADAVEK_TYP" MODIFY ("UZIV_I" NOT NULL ENABLE);
