--------------------------------------------------------
--  Constraints for Table UKOLY
--------------------------------------------------------

  ALTER TABLE "HR"."UKOLY" MODIFY ("DATUM_I" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."UKOLY" MODIFY ("UZIV_I" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."UKOLY" ADD CHECK (UKOL_POSLENDI IN ('Y','N')) ENABLE;
 
  ALTER TABLE "HR"."UKOLY" ADD CONSTRAINT "UKOLY_ID_PK" PRIMARY KEY ("UKOLY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
