--------------------------------------------------------
--  Constraints for Table UKOL_TYP
--------------------------------------------------------

  ALTER TABLE "HR"."UKOL_TYP" MODIFY ("DATUM_I" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."UKOL_TYP" MODIFY ("UZIV_I" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."UKOL_TYP" MODIFY ("UKOL_TYP" CONSTRAINT "UKOL_TYPU_NN" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."UKOL_TYP" ADD CONSTRAINT "UKOL_TYP_ID_PK" PRIMARY KEY ("UKOL_TYP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."UKOL_TYP" ADD CONSTRAINT "UKOL_TYP_UK" UNIQUE ("UKOL_TYP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
