--------------------------------------------------------
--  Constraints for Table UZIVATEL
--------------------------------------------------------

  ALTER TABLE "HR"."UZIVATEL" MODIFY ("DATUM_I" CONSTRAINT "DATUM_I_NN" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."UZIVATEL" MODIFY ("EMAIL" CONSTRAINT "EMAIL_NN" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."UZIVATEL" MODIFY ("JMENO" CONSTRAINT "JMENO_NN" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."UZIVATEL" MODIFY ("UZIV_I" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."UZIVATEL" ADD CONSTRAINT "UZIVATEL_ID_PK" PRIMARY KEY ("UZIVATEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."UZIVATEL" ADD CONSTRAINT "UZIV_EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
