--------------------------------------------------------
--  DDL for Table POSLEDNI_UKOL_POZADAVKU
--------------------------------------------------------

  CREATE TABLE "HR"."POSLEDNI_UKOL_POZADAVKU" 
   (	"UKOLY_ID" NUMBER, 
	"POZADAVKY_ID" NUMBER, 
	"DATUM_I" DATE, 
	"DATUM_U" DATE, 
	"UZIV_I" VARCHAR2(30 BYTE), 
	"UZIV_U" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "HR"."POSLEDNI_UKOL_POZADAVKU"."UKOLY_ID" IS 'Cizi klic na UKOLY.UKOLY_ID';
 
   COMMENT ON COLUMN "HR"."POSLEDNI_UKOL_POZADAVKU"."POZADAVKY_ID" IS 'Cizi klic na POZADAVKY.POZADAVKY_ID';
 
   COMMENT ON COLUMN "HR"."POSLEDNI_UKOL_POZADAVKU"."DATUM_I" IS 'Datum zalozeni posledniho ukolu';
 
   COMMENT ON COLUMN "HR"."POSLEDNI_UKOL_POZADAVKU"."DATUM_U" IS 'Datum upravy posledniho ukolu.';
