--------------------------------------------------------
--  Ref Constraints for Table POSLEDNI_UKOL_POZADAVKU
--------------------------------------------------------

  ALTER TABLE "HR"."POSLEDNI_UKOL_POZADAVKU" ADD CONSTRAINT "POSLEDNI_UKOL_POZADAVKY_ID_FK" FOREIGN KEY ("POZADAVKY_ID")
	  REFERENCES "HR"."POZADAVKY" ("POZADAVKY_ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "HR"."POSLEDNI_UKOL_POZADAVKU" ADD CONSTRAINT "POSLEDNI_UKOL_UKOL_ID_FK" FOREIGN KEY ("UKOLY_ID")
	  REFERENCES "HR"."UKOLY" ("UKOLY_ID") ON DELETE SET NULL ENABLE;
