--------------------------------------------------------
--  Ref Constraints for Table UKOLY
--------------------------------------------------------

  ALTER TABLE "HR"."UKOLY" ADD CONSTRAINT "POZADAVKY_ID_FK" FOREIGN KEY ("POZADAVKY_ID")
	  REFERENCES "HR"."POZADAVKY" ("POZADAVKY_ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "HR"."UKOLY" ADD CONSTRAINT "UKOL_STAV_ID_FK" FOREIGN KEY ("UKOL_STAV_ID")
	  REFERENCES "HR"."UKOL_STAV" ("UKOL_STAV_ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "HR"."UKOLY" ADD CONSTRAINT "UKOL_TYP_ID_FK" FOREIGN KEY ("UKOL_TYP_ID")
	  REFERENCES "HR"."UKOL_TYP" ("UKOL_TYP_ID") ON DELETE SET NULL ENABLE;
 
  ALTER TABLE "HR"."UKOLY" ADD CONSTRAINT "UZIVATEL_ID_FK" FOREIGN KEY ("UZIVATEL_ID")
	  REFERENCES "HR"."UZIVATEL" ("UZIVATEL_ID") ON DELETE SET NULL ENABLE;
