--------------------------------------------------------
--  DDL for View V_POZADAVKY
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "HR"."V_POZADAVKY" ("POZADAVKY_ID", "JEDNACI_CISLO", "DATUM_ZALOZENI", "DATUM_UKONCENI", "POZADAVEK_STAV_ID", "POZADAVEK_STAV", "POZADAVEK_TYP_ID", "POZADAVEK_TYP", "POPIS_POZADAVKU", "POSLEDNI_UKOL_ID", "POSLEDNI_UKOL_UZIVATEL_ID", "POSLEDNI_UKOL_UZIVATEL", "POSLEDNI_UKOL_TYP_ID", "POSLEDNI_UKOL_TYP") AS 
  SELECT 
POZADAVKY.POZADAVKY_ID,
POZADAVKY.JEDNACI_CISLO,
POZADAVKY.DATUM_ZALOZENI,
POZADAVKY.DATUM_UKONCENI,
POZADAVKY.POZADAVEK_STAV_ID,
POZADAVKY.POZADAVEK_STAV,
POZADAVKY.POZADAVEK_TYP_ID,
POZADAVKY.POZADAVEK_TYP,
POZADAVKY.POPIS_POZADAVKU,
POSLEDNIUKOL.POSLEDNI_UKOL_ID,
POSLEDNIUKOL.POSLEDNI_UKOL_UZIVATEL_ID,
POSLEDNIUKOL.POSLEDNI_UKOL_UZIVATEL,
POSLEDNIUKOL.POSLEDNI_UKOL_TYP_ID,
POSLEDNIUKOL.POSLEDNI_UKOL_TYP
FROM 
(SELECT
  P.POZADAVKY_ID, P.JEDNACI_CISLO, P.DATUM_I DATUM_ZALOZENI, P.DATUM_UKONCENI,
  PS.POZADAVEK_STAV_ID, PS.POZADAVEK_STAV,  PT.POZADAVEK_TYP_ID,PT.POZADAVEK_TYP, P.POPIS_POZADAVKU
 FROM HR.POZADAVKY P, HR.POZADAVEK_TYP PT, HR.POZADAVEK_STAV PS
 WHERE
  P.POZADAVEK_TYP_ID = PT.POZADAVEK_TYP_ID
  AND P.POZADAVEK_STAV_ID = PS.POZADAVEK_STAV_ID
) POZADAVKY
,--OUTER APPLY
(SELECT 
  UK.UKOLY_ID POSLEDNI_UKOL_ID,UK.POZADAVKY_ID,UZ.UZIVATEL_ID POSLEDNI_UKOL_UZIVATEL_ID, UZ.PRIJMENI POSLEDNI_UKOL_UZIVATEL, 
  UT.UKOL_TYP_ID POSLEDNI_UKOL_TYP_ID,UT.UKOL_TYP POSLEDNI_UKOL_TYP
 FROM  HR.UKOLY UK,HR.UKOL_TYP UT,  HR.UZIVATEL UZ
 WHERE UK.UZIVATEL_ID = UZ.UZIVATEL_ID
  AND UK.UKOL_TYP_ID = UT.UKOL_TYP_ID
  AND UK.POZADAVKY_ID =  1--P.POZADAVKY_ID
  AND UK.UKOL_POSLENDI = 'Y' --PREDPOKLAD: v ramci jednoho pozadavku jen jeden zaznam ma byt oznaceny jako posledni 
  AND ROWNUM < 2 --PRO JISTOTU
) POSLEDNIUKOL
WHERE POZADAVKY.POZADAVKY_ID = POSLEDNIUKOL.POZADAVKY_ID
;
